server:
  context-path: /localhost
  servlet-path: /*
  use-forward-headers: true
  tomcat:
    uri-encoding: utf-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  port: 8888
logging:
  level:
    com.wangfan.localhost.dao: debug
spring:
  datasource:
    #公共配置
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/docker?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 1000
      max-active: 1
  redis:
    host: localhost
    port: 6379
    password: redispass
    database: 0
    pool:
      max-active: 1000
      max-wait: 5000
      max-idle: 10
      min-idle: 0
mybatis:
  mapper-locations: classpath*:com/wangfan/localhost/dao/**/*Mapper.xml
  type-aliases-package: com.ejiayou.localhost.dao
executor:
  pool:
    corePoolSize: 20
    maxPoolSize: 30
    queueCapacity: 100
